const records = [
  {
    date: new Date("2022-06-20"), // Use ISO format for dates
    water_height: 0.28,
    catch: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-21"),
    water_height: 0.25,
    catch: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-22"),
    water_height: 0.23,
    catch: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-23"),
    water_height: 0.22,
    catch: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-24"),
    water_height: 0.22,
    catch: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-25"),
    water_height: 1.00,
    catch: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-26"),
    water_height: 1.70,
    catch: 13,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-06-27"), // Use ISO format for dates
    water_height: 1.19,
    catch: 31,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-28"),
    water_height: 0.92,
    catch: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-29"),
    water_height: 1.10,
    catch: 51,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-06-30"),
    water_height: 1.25,
    catch: 34,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-01"),
    water_height: 0.83,
    catch: 39,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-02"),
    water_height: 0.75,
    catch: 33,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-03"),
    water_height: 0.68,
    catch: 36,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-07-25"), // Use ISO format for dates
    water_height: 0.79,
    catch: 16,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-26"),
    water_height: 0.56,
    catch: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-27"),
    water_height: 0.34,
    catch: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-28"),
    water_height: 0.27,
    catch: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-29"),
    water_height: 0.23,
    catch: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-30"),
    water_height: 0.23,
    catch: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-07-31"),
    water_height: 0.30,
    catch: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-08-01"), // Use ISO format for dates
    water_height: 0.24,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-02"),
    water_height: 1.10,
    catch: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-03"),
    water_height: 0.73,
    catch: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-04"),
    water_height: 0.61,
    catch: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-05"),
    water_height: 0.53,
    catch: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-06"),
    water_height: 0.38,
    catch: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-07"),
    water_height: 0.31,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-08-08"), // Use ISO format for dates
    water_height: 0.27,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-09"),
    water_height: 0.24,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-10"),
    water_height: 0.22,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-11"),
    water_height: 0.21,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-12"),
    water_height: 0.20,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-13"),
    water_height: 0.20,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-14"),
    water_height: 0.19,
    catch: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-08-22"), // Use ISO format for dates
    water_height: 0.25,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-23"),
    water_height: 0.29,
    catch: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-24"),
    water_height: 0.24,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-25"),
    water_height: 0.22,
    catch: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-26"),
    water_height: 0.21,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-27"),
    water_height: 0.26,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-28"),
    water_height: 0.21,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-08-29"), // Use ISO format for dates
    water_height: 0.20,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-30"),
    water_height: 0.19,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-08-31"),
    water_height: 0.18,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-01"),
    water_height: 0.18,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-02"),
    water_height: 0.17,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-03"),
    water_height: 0.22,
    catch: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-04"),
    water_height: 0.31,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-09-05"), // Use ISO format for dates
    water_height: 0.55,
    catch: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-06"),
    water_height: 0.43,
    catch: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-07"),
    water_height: 0.42,
    catch: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-08"),
    water_height: 0.54,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-09"),
    water_height: 0.44,
    catch: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-10"),
    water_height: 0.33,
    catch: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-11"),
    water_height: 0.28,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-09-19"), // Use ISO format for dates
    water_height: 0.19,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-20"),
    water_height: 0.19,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-21"),
    water_height: 0.18,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-22"),
    water_height: 0.20,
    catch: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-23"),
    water_height: 0.42,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-24"),
    water_height: 0.26,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-25"),
    water_height: 0.22,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-09-26"),
    water_height: 0.21,
    catch: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-27"),
    water_height: 0.23,
    catch: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-28"),
    water_height: 0.28,
    catch: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    date: new Date("2022-09-29"),
    water_height: 0.52,
    catch: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    date: new Date("2022-09-30"),
    water_height: 0.37,
    catch: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
module.exports = records;